### ISSUE TITLE
Multiple Author Pages

### ISSUE THREAD

**Issue by ogsteele** [eventer-neuroscience/eventer-fresh#1]
Odd bug with the "people" widget where multiple profiles show on the homepage with correct pictures and properly functioning links to socials, however clicking the picture won't take you to the corresponding page - it takes it to a seemingly random profile, repeatedly.

**Comment by ogsteele** [comment]
_index.md/index.md fix for widget pages doesn't fix this issue.

**Comment by amchagas** [comment]
https://github.com/eventer-neuroscience/eventer-fresh/commit/caaf59b60c1d674da0ccef4547b0847885839309 solves this. 
It was an issue with config.toml
it pointed to `authors` when it should point to `content/authors`
