### ISSUE TITLE
Add Plausible.io to Eventer?

### ISSUE THREAD

**Issue by amchagas** [eventer-neuroscience/eventer-fresh#7]
Hi!

I am currently using plausible.io as the traffic measurement tool for my websites (personal and open-neuroscience.com). The nice thing about it is that it respects users privacy, does not require cookies, notice to users, etc.  Also the stats can be made open to everyone: https://plausible.io/open-neuroscience.com

This is a paid service, but still cheap enough to be attractive for starting/indy projects like the ones I am developing on the side. That said, I could add Eventer website to my account, make the stats open so that we can see how Eventer does over time?

**Comment by ogsteele** [comment]
Apologies, somehow only saw this now! That sounds amazing, how much is your membership @amchagas? I don't want to feel like I'm taking advantage of you!

**Comment by amchagas** [comment]
not at all!
the membership is not expensive, and we are nowhere near the max visits allowed by it... If it starts to be an issue we can circle back and see how to move things forward. 
I'll add the website to plausible.io and let you know! (most likely tomorrow)

**Comment by ogsteele** [comment]
Excellent, let me know - I'll be really interested to see what it spits out!

**Comment by amchagas** [comment]
added with this push https://github.com/eventer-neuroscience/eventer-fresh/commit/af38371ff737304782c57684962df9363f65bf0e

**Comment by amchagas** [comment]
stats can be publicly viewed here https://plausible.io/eventerneuro.netlify.app

**Comment by ogsteele** [comment]
Very cool - thanks for this!!
